name: cat_breeds
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  domain:
    path: ./modules/domain
  infrastructure:
    path: ./modules/infrastructure
  flutter:
    sdk: flutter    
  cupertino_icons: ^1.0.8
  get_it: ^9.2.1
  injectable: ^3.0.0
  flutter_riverpod: ^3.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^3.0.2
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  generate: true

fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/cat.png"