name: infrastructure
description: A starting point for Dart libraries or applications.
publish_to: 'none' 
version: 1.0.0

environment:
  sdk: ^3.10.8

dependencies:
  domain:
   path: ../domain
  internet_connection_checker: ^1.0.0+1
  dio: ^5.9.0
  get_it: ^8.2.0
  injectable: ^2.5.1
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  injectable_generator: 
  json_serializable: ^6.9.0
